### ISSUE TITLE
UnrealGT won't compile on UE5.1

### ISSUE THREAD

**Issue by ChristianWiele** [unrealgt/unrealgt#22]
Hi,

when compiling UnrealGT on UE5.1 I get an error
`In file included from /Volumes/WorkSSD/Unreal Projects/Ocean_5_1/Plugins/unrealgt/Intermediate/Build/Mac/x86_64/UnrealEditor/Development/UnrealGT/Module.UnrealGT.cpp:38:
/Volumes/WorkSSD/Unreal Projects/Ocean_5_1/Plugins/unrealgt/Source/UnrealGT/Private/GTGeneratorReferenceCustomization.cpp:85:22: error: use of undeclared identifier 'FEditorStyle'
        Info.Image = FEditorStyle::GetBrush(TEXT("MessageLog.Warning"));`

I could fix it by adding 
`#include "EditorStyleSet.h"`
to the GTGeneratorReferenceCustomization.cpp file.

Regards, Christian

**Comment by james-yoo** [comment]
Thanks, @ChristianWiele
You saved my time!

**Comment by Shromm-Gaind** [comment]
I found a repository that worked for me on unreal 5.1. It doesn't have a fork of this repository but thought it best to let you guys know.  https://github.com/dragonheat123/unrealgt_ue5

**Comment by StuartGJohnson** [comment]
Seems we should have a UE5/5.1 branch of this repo. Any opinions? Let me check the differences with dragonheat123's code.
